#!/bin/sh
# Copyright (C) 2018 Open Source Foundries Ltd.
# Licensed on MIT

ostree_enabled() {
	return 0
}

ostree_run() {
	if [ -n "$ROOTFS_DIR" ]; then
		if [ -n "$bootparam_composefs" ]; then
			[ ! -d /etc/ostree ] && msg "No initramfs composefs module found"
			. /etc/ostree/composefs

			ostree_composefs_prepare
		fi

		msg "Preparing OSTree root at '$ROOTFS_DIR'..."
		/usr/lib/ostree/ostree-prepare-root $ROOTFS_DIR
	else
		debug "No rootfs has been set"
	fi
}
