#!/bin/sh
# Copyright (C) 2018 Open Source Foundries Ltd.
# Licensed on MIT

ostree_enabled() {
	return 0
}

ostree_run() {
	if [ -n "$ROOTFS_DIR" ]; then
		# Check if composefs was configured
		if [ -e /usr/lib/ostree/prepare-root.conf ]; then
			composefs=$(sed -n '/\[composefs\]/{:a;n;/enabled/{s/.*=//p;q};ba}' /usr/lib/ostree/prepare-root.conf)
			msg "CFS = $composefs "
			if [ "$composefs" == "signed"]; then
				# Check if the composefs module is present
				[ ! -e /etc/ostree/composefs ] && fatal "No initramfs composefs module found"
				. /etc/ostree/composefs
				ostree_composefs_prepare
			fi
		fi

		msg "Preparing OSTree root at '$ROOTFS_DIR'..."
		/usr/lib/ostree/ostree-prepare-root $ROOTFS_DIR
	else
		debug "No rootfs has been set"
	fi
}
